//todolist功能实现
const CHANGE_MSG='CHANGE_MSG'
const TODO_ADD='TODO_ADD'
const TODO_UPD='TODO_UPD'
const TODO_DET='TODO_DET'
const TODO_CLEAR='TODO_CLEAR'
//用户管理
const GET_USER_LIST='GET_USER_LIST'
//商品管理
const GET_SHOP_LIST='GET_SHOP_LIST'
const GET_CATE='GET_CATE'
const GET_DETIAL="GET_DETIAL"
export {
    CHANGE_MSG,
    TODO_ADD,
    TODO_UPD,
    TODO_DET,
    TODO_CLEAR,
    GET_USER_LIST,
    GET_SHOP_LIST,
    GET_CATE,
    GET_DETIAL
}